### PR TITLE
Add missing whitespace in stdlib output

### PR DESCRIPTION
**Pull request by ahoarau**
Fixes the stdlib output

image

### CODE REVIEW

**Comment by jfalcou** [comment]
See https://github.com/jfalcou/spy/blob/main/src/spy/stdlib.hpp

**Comment by jfalcou** [comment]
This reminds me I should probably add à doc page on how to contribute

**Comment by ahoarau** [comment]
Done 👍

**Review by jfalcou — APPROVED** [review]

**Comment by jfalcou** [comment]
Thanks!

**Pull request merged**
